# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16, unique=True, verbose_name='short name')),
                ('app_namespace', models.CharField(max_length=16)),
                ('singular_title', models.CharField(blank=True, default='', max_length=32)),
                ('plural_title', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
    ]
