# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16, unique=True, verbose_name='Content type short name')),
                ('app_namespace', models.CharField(max_length=16)),
                ('singular_title', models.CharField(blank=True, default='', max_length=32)),
                ('plural_title', models.CharField(blank=True, default='', max_length=32)),
                ('menu_level', models.IntegerField(choices=[(1, 'Main Menu'), (2, 'Supporting Menu'), (3, 'Not on menu')], default=1)),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
            ],
            options={
                'ordering': ['menu_level', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('contact', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['institution'],
            },
        ),
    ]
