# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='slug',
            field=models.SlugField(max_length=16, unique=True, verbose_name='Content type short name'),
        ),
    ]
