# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160201_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='menu_level',
            field=models.IntegerField(choices=[(1, 'Main Menu'), (2, 'Supporting Menu')], default=1),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='ordinal',
            field=models.IntegerField(default=99, verbose_name='Order in Menu'),
        ),
    ]
