# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160527_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttype',
            options={'ordering': ['menu_level', 'ordinal']},
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='menu_level',
            field=models.IntegerField(choices=[(1, 'Main Menu'), (2, 'Supporting Menu'), (3, 'Not on menu')], default=1),
        ),
    ]
