# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160630_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('contact', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
    ]
