# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-08 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['institution']},
        ),
    ]
