# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_narrative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
