# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(max_length=48, unique=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='story',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=48),
        ),
    ]
