# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20160201_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='introduction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='menu_blurb',
            field=models.TextField(blank=True, default=''),
        ),
    ]
