# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models

# edited by hand to remove refs to evidence_evidenceitem and people_person

class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20160204_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='narrative',
            field=models.TextField(blank=True, default=''),
        ),
    ]
