# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20160204_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='evidence_item',
            new_name='evidence',
        ),
    ]
