# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20160204_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['story', 'chapter_num']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='people',
        ),
    ]
