# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0001_initial'),
        ('stories', '0006_auto_20160226_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='people',
            field=models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item'),
        ),
    ]
