# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0002_context'),
        ('stories', '0007_auto_20160228_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item'),
        ),
    ]
