# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_chapter_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
