# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_chapter_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_num',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='story',
            name='status_num',
            field=models.IntegerField(choices=[(1, '1 - In Admin Only'), (2, '2 - Development (Wireframe)'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
    ]
