# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_auto_20160509_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_num',
            field=models.IntegerField(default=0),
        ),
    ]
