# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20160623_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In Admin Only'), (2, '2 - Development (Wireframe)'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
    ]
