# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_source'),
        ('stories', '0013_auto_20160630_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AddField(
            model_name='story',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption'),
        ),
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption'),
        ),
    ]
