# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0011_auto_20160713_1531'),
        ('stories', '0014_auto_20160709_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='fastfacts',
            field=models.ManyToManyField(blank=True, to='supporting.FastFact', verbose_name='Fast Facts related to this item'),
        ),
    ]
