# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0012_auto_20160907_1422'),
        ('stories', '0015_chapter_fastfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='special_features',
            field=models.ManyToManyField(blank=True, to='supporting.Special', verbose_name='Special Features related to this item'),
        ),
    ]
