# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_chapter_featured_specials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='featured_specials',
            field=models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='special_features',
            field=models.ManyToManyField(blank=True, to='supporting.Special', verbose_name='OBSOLETE Special Features related to this item'),
        ),
    ]
