# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0020_auto_20170301_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='special_features',
        ),
    ]
