# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_remove_chapter_special_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='has_include',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='include_path',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
