# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_auto_20170321_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='has_include',
            field=models.BooleanField(default=False, verbose_name='Use include instead of image'),
        ),
    ]
