# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_artifact_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
    ]
