# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_auto_20160204_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenceitem',
            old_name='description',
            new_name='narrative',
        ),
    ]
