# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_auto_20160224_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenceitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='evidenceitem',
            name='evidence_type',
        ),
        migrations.DeleteModel(
            name='EvidenceItem',
        ),
        migrations.DeleteModel(
            name='EvidenceType',
        ),
    ]
