# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('special', '0001_initial'),
        ('supporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Layer short name')),
                ('era_description', models.CharField(blank=True, default='', max_length=128)),
                ('layer_blurb', models.TextField(blank=True, default='')),
                ('layer_identifier', models.CharField(blank=True, default='', max_length=64)),
                ('layer_index', models.IntegerField(default=0, verbose_name='Base layer index')),
                ('ordinal', models.IntegerField(default=99, verbose_name='List order')),
                ('contexts', models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item')),
                ('evidence', models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item')),
                ('featured_specials', models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item')),
                ('people', models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item')),
                ('places', models.ManyToManyField(blank=True, to='supporting.Place')),
            ],
            options={
                'verbose_name': 'Location Set',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Overlay short name')),
                ('map_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='List order')),
                ('layer_index', models.IntegerField(default=0, verbose_name='Overlay layer index')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
    ]
