# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('layer_identifier', models.CharField(blank=True, default='', max_length=64)),
                ('layer_blurb', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('evidenceitem', 'Evidence'), ('context', 'Context')], max_length=16)),
                ('short_name', models.CharField(max_length=48, verbose_name='Short name of the evidence, context, etc.')),
                ('latitude', models.FloatField(blank=True, help_text="Decimal degrees. Right click on google maps - What's Here.", null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Decimal degrees, U.S. negative', null=True)),
            ],
        ),
    ]
