# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0004_auto_20160317_1755'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item'),
        ),
        migrations.AddField(
            model_name='layer',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item'),
        ),
        migrations.AddField(
            model_name='layer',
            name='people',
            field=models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item'),
        ),
        migrations.AddField(
            model_name='layer',
            name='sites',
            field=models.ManyToManyField(blank=True, to='map.Site', verbose_name='Sites relevant to this layer'),
        ),
    ]
