# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160406_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='slug',
            field=models.SlugField(default='today', max_length=32, verbose_name='Layer short name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('evidenceitem', 'Evidence'), ('context', 'Context'), ('place', 'Place of Interest'), ('special', 'Special Feature')], max_length=16),
        ),
    ]
