# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20160716_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='layer_index',
            field=models.IntegerField(default=0),
        ),
    ]
