# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20161208_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Overlay short name')),
                ('map_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order of Eras')),
                ('layer_index', models.IntegerField(default=0, verbose_name='Overlay layer index')),
            ],
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['ordinal'], 'verbose_name': 'Location Set'},
        ),
    ]
