# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0026_auto_20170301_1054'),
        ('map', '0009_auto_20170110_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='places',
            field=models.ManyToManyField(blank=True, to='supporting.Place'),
        ),
    ]
