# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_layer_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='sites',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
