# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0005_auto_20170430_1951'),
        ('map', '0011_auto_20170317_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='featured_specials',
            field=models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item'),
        ),
    ]
