# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
