# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='status_num',
            field=models.IntegerField(choices=[(1, '1 - In Admin Only'), (2, '2 - Development (Wireframe)'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
    ]
