# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20160709_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
