# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_auto_20170218_1745'),
        ('themes', '0005_theme_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='featured_specials',
            field=models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item'),
        ),
    ]
