# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 23:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('menu_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Production Notes')),
                ('edited_by', models.CharField(blank=True, default='', max_length=64)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='edit date')),
                ('status_num', models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption')),
                ('special_type', models.CharField(choices=[('slideshow', 'Slideshow'), ('video', 'Video Story'), ('voices', 'Voices'), ('looking', 'Looking &amp; Seeing'), ('then', 'Then &amp; Now'), ('footprint', 'Activity: Footprints'), ('explore', 'Activity: Explore'), ('discoverers', 'Whose Discovery'), ('society', 'Activity: Ladies Literary Society')], default='slideshow', max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('narrative', models.TextField(blank=True, default='', verbose_name='Narrative / Label')),
                ('map_blurb', models.TextField(blank=True, default='')),
                ('is_on_menu', models.BooleanField(default=True, verbose_name='Show on Special Features Menu')),
                ('img_width', models.IntegerField(blank=True, null=True, verbose_name='img width (or runtime)')),
                ('img_height', models.IntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='core.ContentType')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source')),
            ],
            options={
                'verbose_name': 'Special Feature',
                'ordering': ['special_type', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_num', models.IntegerField()),
                ('image_name', models.CharField(blank=True, default='', max_length=32, verbose_name='image short name')),
                ('caption', models.CharField(blank=True, default='', help_text='For each slide -- Slides ignore Caption at top of form.', max_length=255)),
                ('narrative', models.TextField(blank=True, default='', help_text='caption for each slide -- slides ignore Narrative at top of form.')),
                ('num_correct', models.IntegerField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special.Feature')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source')),
            ],
            options={
                'ordering': ['slide_num'],
            },
        ),
    ]
