# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-18 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='special',
            new_name='feature',
        ),
    ]
