# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_auto_20170218_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_on_menu',
            field=models.BooleanField(default=True, verbose_name='Show on Special Feature Menu'),
        ),
    ]
