# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0003_feature_is_on_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='is_on_menu',
            field=models.BooleanField(default=True, verbose_name='Show on Special Features Menu'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='special_type',
            field=models.CharField(choices=[('slideshow', 'Slideshow'), ('video', 'Video Story'), ('voices', 'Voices'), ('looking', 'Looking &amp; Seeing'), ('then', 'Then &amp; Now'), ('footprint', 'Activity: Footprints'), ('explore', 'Activity: Explore'), ('discoverers', 'Whose Discovery')], default='slideshow', max_length=32),
        ),
    ]
