# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0004_auto_20170317_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='special_type',
            field=models.CharField(choices=[('slideshow', 'Slideshow'), ('video', 'Video Story'), ('voices', 'Voices'), ('looking', 'Looking &amp; Seeing'), ('then', 'Then &amp; Now'), ('footprint', 'Activity: Footprints'), ('explore', 'Activity: Explore'), ('discoverers', 'Whose Discovery'), ('society', 'Activity: Ladies Literary Society')], default='slideshow', max_length=32),
        ),
    ]
