# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0005_auto_20170430_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0),
        ),
    ]
