# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0006_auto_20170523_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='img_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='img_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
