# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0007_auto_20170526_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['special_type', 'ordinal'], 'verbose_name': 'Special Feature'},
        ),
    ]
