# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0008_auto_20170601_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='img_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='img width (or runtime)'),
        ),
    ]
