# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 23:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('menu_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Production Notes')),
                ('edited_by', models.CharField(blank=True, default='', max_length=64)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='edit date')),
                ('status_num', models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption')),
                ('context_type', models.CharField(choices=[('Background', 'Background'), ('Institution', 'Institution')], default='Background', max_length=24)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(blank=True, default='', max_length=128)),
                ('narrative', models.TextField(blank=True, default='', verbose_name='Description / Label')),
                ('map_blurb', models.TextField(blank=True, default='')),
                ('priority_num', models.IntegerField(choices=[(1, '1 - highest priority'), (2, '2 - important'), (3, '3 - nice to have'), (5, '5 - TBD'), (9, '9 - not using')], default=5)),
                ('author', models.CharField(blank=True, default='', max_length=16)),
                ('content_type', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='core.ContentType')),
                ('contexts', models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item')),
            ],
            options={
                'verbose_name': 'Backdrop',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('menu_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Production Notes')),
                ('edited_by', models.CharField(blank=True, default='', max_length=64)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='edit date')),
                ('status_num', models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(blank=True, default='', max_length=128)),
                ('narrative', models.TextField(blank=True, default='', verbose_name='Description / Label')),
                ('creator', models.CharField(blank=True, default='', max_length=64, verbose_name='maker/author')),
                ('creation_year', models.CharField(blank=True, max_length=128, null=True, verbose_name='Date')),
                ('is_circa', models.BooleanField(default=False)),
                ('dimensions', models.CharField(blank=True, default='', max_length=128)),
                ('materials', models.CharField(blank=True, default='', max_length=128)),
                ('accession_num', models.CharField(blank=True, default='', max_length=128)),
                ('map_blurb', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.ContentType')),
                ('contexts', models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item')),
                ('evidence', models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_document_oriented', models.BooleanField(verbose_name='Document-oriented: can have pages and or transcripts')),
                ('title', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=16, unique=True)),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='FastFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('menu_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Production Notes')),
                ('edited_by', models.CharField(blank=True, default='', max_length=64)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='edit date')),
                ('status_num', models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption')),
                ('fastfact_type', models.CharField(choices=[('definition', 'Definition'), ('moreinfo', 'More Info')], default='moreinfo', max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('narrative', models.TextField(blank=True, default='', verbose_name='Description / Label')),
                ('has_image', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='core.ContentType')),
                ('evidence', models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence item for this In Brief')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source')),
            ],
            options={
                'verbose_name': 'In Brief',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField(verbose_name='page order')),
                ('page_suffix', models.CharField(blank=True, default='', max_length=64, verbose_name='filename suffix')),
                ('page_label', models.CharField(blank=True, default='', max_length=64, verbose_name='page label')),
                ('transcript', models.TextField(blank=True, default='', help_text='Transcription per page')),
                ('evidenceitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting.EvidenceItem')),
            ],
            options={
                'verbose_name': 'Document Page',
                'ordering': ['page_num'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('menu_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Production Notes')),
                ('edited_by', models.CharField(blank=True, default='', max_length=64)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='edit date')),
                ('status_num', models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption')),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('middle_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('title_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('suffix', models.CharField(blank=True, default='', max_length=16)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True, default='')),
                ('person_level', models.IntegerField(choices=[(0, 'Minor'), (1, 'Secondary'), (2, 'Primary'), (9, 'Not Using')], default=0)),
                ('has_image', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.ContentType')),
                ('contexts', models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item')),
                ('evidence', models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item')),
                ('featured_specials', models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item')),
                ('people', models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('menu_blurb', models.TextField(blank=True, default='')),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order in Menu')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Production Notes')),
                ('edited_by', models.CharField(blank=True, default='', max_length=64)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='edit date')),
                ('status_num', models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Image Caption')),
                ('title', models.CharField(max_length=128)),
                ('narrative', models.TextField(blank=True, default='', verbose_name='Description / Label')),
                ('map_blurb', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, help_text="Decimal degrees. Right click on google maps - What's Here.", null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Decimal degrees, U.S. negative', null=True)),
                ('content_type', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='core.ContentType')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source')),
            ],
            options={
                'verbose_name': 'Place of Interest',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=24, unique=True, verbose_name='Topic short name')),
                ('title', models.CharField(max_length=64)),
                ('ordinal', models.IntegerField(default=99, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Backdrop Topic/Category',
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='evidence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting.EvidenceType'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='featured_specials',
            field=models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='people',
            field=models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AddField(
            model_name='context',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item'),
        ),
        migrations.AddField(
            model_name='context',
            name='featured_specials',
            field=models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item'),
        ),
        migrations.AddField(
            model_name='context',
            name='people',
            field=models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item'),
        ),
        migrations.AddField(
            model_name='context',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AddField(
            model_name='context',
            name='topics',
            field=models.ManyToManyField(blank=True, to='supporting.Topic', verbose_name='Topics related to this backdrop'),
        ),
    ]
