# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0002_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item'),
        ),
        migrations.AddField(
            model_name='context',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item'),
        ),
        migrations.AddField(
            model_name='context',
            name='people',
            field=models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='people',
            field=models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item'),
        ),
        migrations.AddField(
            model_name='person',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='supporting.Context', verbose_name='Contexts related to this item'),
        ),
        migrations.AddField(
            model_name='person',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence items related to this item'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='people',
            field=models.ManyToManyField(blank=True, to='supporting.Person', verbose_name='People related to this item'),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='is_document_oriented',
            field=models.BooleanField(verbose_name='Document-oriented: can have pages         and/or transcripts'),
        ),
    ]
