# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0004_auto_20160317_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='status_num',
            field=models.IntegerField(choices=[(1, '1 - Place Holder'), (2, '2 - Real Shortname'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='status_num',
            field=models.IntegerField(choices=[(1, '1 - Place Holder'), (2, '2 - Real Shortname'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='is_document_oriented',
            field=models.BooleanField(verbose_name='Document-oriented: can have pages and or transcripts'),
        ),
        migrations.AlterField(
            model_name='fastfact',
            name='status_num',
            field=models.IntegerField(choices=[(1, '1 - Place Holder'), (2, '2 - Real Shortname'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='status_num',
            field=models.IntegerField(choices=[(1, '1 - Place Holder'), (2, '2 - Real Shortname'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
    ]
