# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0005_auto_20160518_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='context_type',
            field=models.CharField(choices=[('Background', 'Background'), ('Institution', 'Institution')], default='Background', max_length=24),
        ),
    ]
