# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0007_auto_20160630_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'Special Feature'},
        ),
    ]
