# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0010_auto_20160713_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='map_blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='map_blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='map_blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='special',
            name='map_blurb',
            field=models.TextField(blank=True, default=''),
        ),
    ]
