# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0011_auto_20160713_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterModelOptions(
            name='evidenceitem',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'ordering': ['ordinal'], 'verbose_name': 'Special Feature'},
        ),
        migrations.AlterField(
            model_name='special',
            name='special_type',
            field=models.CharField(choices=[('audio', 'Voices'), ('interactive', 'Interactive'), ('looking', 'Looking &amp; Seeing'), ('slideshow', 'Slideshow'), ('then', 'Then &amp; Now'), ('video', 'Video Story')], default='animation', max_length=32),
        ),
    ]
