# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0011_auto_20160713_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_num', models.IntegerField()),
                ('image_name', models.CharField(blank=True, default='', max_length=32)),
                ('credit_line', models.CharField(blank=True, default='', help_text='For each slide -- Slides ignore Credit Line at top of form.', max_length=128)),
                ('narrative', models.TextField(blank=True, default='', help_text='caption for each slide -- slides ignore Narrative at top of form.', verbose_name='Caption')),
            ],
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterModelOptions(
            name='evidenceitem',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'ordering': ['ordinal'], 'verbose_name': 'Special Feature'},
        ),
        migrations.AlterField(
            model_name='special',
            name='special_type',
            field=models.CharField(choices=[('audio', 'Voices'), ('interactive', 'Interactive'), ('looking', 'Looking &amp; Seeing'), ('slideshow', 'Slideshow'), ('then', 'Then &amp; Now'), ('video', 'Video Story')], default='animation', max_length=32),
        ),
        migrations.AddField(
            model_name='slide',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting.Special'),
        ),
    ]
