# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0012_auto_20160907_1422'),
        ('supporting', '0012_auto_20160907_0957'),
    ]

    operations = [
    ]
