# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0013_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='num_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
