# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_source'),
        ('supporting', '0014_slide_num_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastfact',
            options={'verbose_name': 'In Brief'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slide_num']},
        ),
        migrations.AddField(
            model_name='slide',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='credit_line',
            field=models.CharField(blank=True, default='', help_text='For each slide -- Slides ignore Caption at top of form.', max_length=255),
        ),
        migrations.AlterField(
            model_name='slide',
            name='narrative',
            field=models.TextField(blank=True, default='', help_text='caption for each slide -- slides ignore Narrative at top of form.'),
        ),
        migrations.AlterField(
            model_name='special',
            name='special_type',
            field=models.CharField(choices=[('voices', 'Voices'), ('interactive', 'Interactive'), ('looking', 'Looking &amp; Seeing'), ('slideshow', 'Slideshow'), ('then', 'Then &amp; Now'), ('video', 'Video Story')], default='animation', max_length=32),
        ),
    ]
