# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0015_auto_20161020_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='credit_line',
            new_name='caption',
        ),
    ]
