# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0016_auto_20161020_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='image short name'),
        ),
        migrations.AlterField(
            model_name='special',
            name='narrative',
            field=models.TextField(blank=True, default='', verbose_name='Narrative / Label'),
        ),
    ]
