# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0018_person_person_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('page_suffix', models.CharField(blank=True, default='', max_length=64, verbose_name='filename suffix')),
                ('page_label', models.CharField(blank=True, default='', max_length=64, verbose_name='page label')),
                ('transcript', models.TextField(blank=True, default='', help_text='Transcription per page')),
                ('evidenceitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting.EvidenceItem')),
            ],
            options={
                'ordering': ['page_num'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='person_level',
            field=models.IntegerField(choices=[(0, 'Related'), (1, 'Important'), (2, 'Hitchcocks')], default=0),
        ),
    ]
