# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0019_auto_20161208_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_num'], 'verbose_name': 'Document Page'},
        ),
        migrations.AlterField(
            model_name='page',
            name='page_num',
            field=models.IntegerField(verbose_name='page order'),
        ),
    ]
