# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0021_auto_20170110_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='topics',
            field=models.ManyToManyField(blank=True, to='supporting.Topic', verbose_name='Topics related to this backdrop'),
        ),
    ]
