# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0023_auto_20170110_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='author',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='context',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='fastfact',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='special',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
    ]
