# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0024_auto_20170119_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='fastfact',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_level',
            field=models.IntegerField(choices=[(0, 'Minor'), (1, 'Secondary'), (2, 'Primary'), (9, 'Not Using')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AlterField(
            model_name='special',
            name='special_type',
            field=models.CharField(choices=[('slideshow', 'Slideshow'), ('video', 'Video Story'), ('voices', 'Voices'), ('looking', 'Looking &amp; Seeing'), ('then', 'Then &amp; Now'), ('footprint', 'Activity: Footprints'), ('explore', 'Activity: Explore')], default='slideshow', max_length=32),
        ),
        migrations.AlterField(
            model_name='special',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
    ]
