# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0025_auto_20170218_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Decimal degrees. Right click on google maps - What's Here.", null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees, U.S. negative', null=True),
        ),
    ]
