# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_remove_chapter_special_features'),
        ('supporting', '0026_auto_20170301_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='source',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='special',
        ),
        migrations.RemoveField(
            model_name='special',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='special',
            name='source',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-latitude'], 'verbose_name': 'Place of Interest'},
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Special',
        ),
    ]
