# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0027_auto_20170317_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastfact',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='supporting.EvidenceItem', verbose_name='Evidence item for this In Brief'),
        ),
    ]
