# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting', '0028_fastfact_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='creation_year',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0),
        ),
        migrations.AlterField(
            model_name='fastfact',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Not Using'), (1, '1 - In-progress'), (2, '2 - Drafted'), (3, '3 - Content Signed-off'), (4, '4 - Ready for Publication')], default=0),
        ),
    ]
