# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0008_auto_20170601_1527'),
        ('supporting', '0029_auto_20170523_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': 'Place of Interest'},
        ),
        migrations.AddField(
            model_name='person',
            name='featured_specials',
            field=models.ManyToManyField(blank=True, to='special.Feature', verbose_name='Special Features related to this item'),
        ),
    ]
