# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description - Label')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Production Notes')),
                ('status_num', models.IntegerField(choices=[(1, '1 - Entered'), (2, '2 - TBD'), (3, '3 - Work in progress'), (4, '4 - Published')], default=0)),
            ],
        ),
    ]
